spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    repair: true
  datasource:
    url: jdbc:mysql://192.168.248.208:3306/mcp_registry
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver